IO/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('diary.urls')),
]

diary/urls.py
from django.conf.urls import url

from . import views

app_name = 'diary'
urlpatterns = [
    url(r'^$', views.login_view, name='login'),
    url(r'^home/$', views.home_view, name='home'),
    url(r'^home/marks$', views.marks_view, name='marks'),
    url(r'^home/frequency$', views.frequency_view, name='frequency'),
    url(r'^home/students$', views.students_view, name='students'),
    url(r'^home/teachers$', views.teachers_view, name='teachers'),
    url(r'^home/marks_t$', views.marks_t_view, name='marks_t'),
    url(r'^home/frequency_t$', views.frequency_t_view, name='frequency_t'),
]

diary/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Subject(models.Model): # Klasa tworząca tabele przedmiotu za pośrednictwem frameworku django  dla bazy danych SQLite
    name = models.CharField(max_length = 30, null=True)  # pole okreslające nazwe
    def __str__(self):    # metoda zwracająca zawartość pola
        return self.name

class Mark(models.Model):# Klasa tworząca tabele oceny za pośrednictwem frameworku django  dla bazy danych SQLite
    student = models.ForeignKey(User, on_delete=models.CASCADE, null=True) # relacja pomiędzy parą tabel
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True) # relacja pomiędzy parą tabel
    mark = models.IntegerField(choices=( #pole ocen
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
                                       ))
    comment = models.CharField(max_length = 50, null=True)
    def __str__(self):# metoda zwracająca zawartość pól
        return self.student.__str__() + " " + self.subject.__str__() + " " + str(self.mark) + " " + self.comment

class Frequency(models.Model):# Klasa tworząca tabele frekwencji za pośrednictwem frameworku django  dla bazy danych SQLite
    student = models.ForeignKey(User, on_delete=models.CASCADE, null=True) # relacja pomiędzy parą tabel
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True)# relacja pomiędzy parą tabel
    date = models.DateField() #pole określające date
    present = models.BooleanField() # pole okreslajace obecność
    def __str__(self): # metoda zwracająca zawartość pól
        return self.student.__str__() + " " + self.subject.__str__() + " " + str(self.date) + " " + str(self.present)

diary/forms.py
from django import forms
from .models import Mark
import re

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(widget=forms.PasswordInput, label="Password", max_length=100)

    patternUsername = re.compile("^[a-z0-9_]+$")
    patternPassword = re.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$")
    
    def clean_username(self):
        data = self.cleaned_data['username']

        if not self.patternUsername.match(data):
            raise forms.ValidationError("Wrong username! Username can contains only lowercase letters, numbers and '_' char.")
        
        if len(data) < 4:
            raise forms.ValidationError("Too short username! Miniumum 4 signs.")

        return data

    def clean_password(self):
        data = self.cleaned_data['password']

        if len(data) < 8:
            raise forms.ValidationError("Too short password! Minimum 8 signs.")
            
        if not self.patternPassword.match(data):
            raise forms.ValidationError("Wrong password! Password must contains at least l lowercase letter, uppercase letter and number.")

        return data

diary/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from .forms import LoginForm
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from .models import Mark, Subject, Frequency
from datetime import date
from django.utils.dateparse import parse_date
 
# Create your views here.

# def login_view(request):
#     if request.method == "POST":
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             return render(request, 'home.html')
#         else:
#             return HttpResponse('Log in error!')
#     else:
#         return render(request, 'diary/login.html')

@login_required
def home_view(request): #metoda obsługująca strone główną
    return render(request, 'diary/base.html') #zwrócenie do templates

def login_view(request): #metoda obsługująca logowanie
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username'] # pobranie loginu z  formularza
            password = form.cleaned_data['password'] # pobranie hasła z formularza
            user = authenticate(request, username=username, password=password) # autoryzacja
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('diary:home'))
            else:
                form = LoginForm()
    else:
        form = LoginForm()

    return render(request, 'diary/login.html', {'form':form}) #zwrócenie do formularza


def marks_view(request): # metoda obslugująca wyswietlanie ocen studentów
    marks = Mark.objects.filter(student = request.user) # pobranie z modelu ocen
    subjects = Subject.objects.all()       # pobranie z modelu przedmiotów
    context = {
        'marks':marks,
        'subjects':subjects,
    }
    return render(request, 'diary/marks.html', context) #zwrócenie do templates

def frequency_view(request): # metoda obsługująca wyświetlanie frekwencji  dla ucznia
    frequency = Frequency.objects.filter(student = request.user) # pobranie z modelu obecności
    today = date.today()#pobranie daty
    context = {
        'today':today,
        'frequency':frequency,
    }
    return render(request, 'diary/frequency.html', context) #zwrócenie do templates
   
def students_view(request):# metoda obsługująca wyśweitlanie listy studentów
    students = User.objects.filter(groups__name = "Students") # pobranie listy sudentów
    return render(request, 'diary/students.html', {'students':students})#zwrócenie do templates

def teachers_view(request): #metoda obsługująca wywietlanie lisy nayczycieli
    teachers = User.objects.filter(groups__name = "Teachers")   # pobranie listy nauczycieli
    return render(request, 'diary/teachers.html', {'teachers':teachers})#zwrócenie do templates

def marks_t_view(request): #wyswietlanie ocen dla widoku nauczyciela
    if request.method == "POST":
        student = request.POST['students']# wyswietlanie listy
        student = User.objects.get(username=student)# wybór z listy
        subject = request.POST['subjects']# wyswietlanie listy
        subject = Subject.objects.get(name=subject)# wybór z listy
        mark = int(request.POST['mark'])# wybór z listy
        comment = request.POST['comment']# pobranie komentarza z formularzu
        Mark.objects.create(student=student,subject=subject,mark=mark,comment=comment)# stworzenie wpisu do bazy
        students = User.objects.filter(groups__name = "Students")#przeszukanie bazy
        subjects = Subject.objects.all()#przeszukanie bazy
        context = {
            'students':students,
            'subjects':subjects,
        }
        return render(request, 'diary/marks_t.html', context)
    else:
        students = User.objects.filter(groups__name = "Students")
        subjects = Subject.objects.all()
        context = {
            'students':students,
            'subjects':subjects,
        }
        return render(request, 'diary/marks_t.html',context)#zwrócenie do templates

def frequency_t_view(request): #wyswietlanie frekwencji dla widoku nauczyciela
    if request.method == "POST":
        student = request.POST['students'] # wyswietlanie listy
        student = User.objects.get(username=student)# wybór z listy
        subject = request.POST['subjects']# wyswietlanie listy
        subject = Subject.objects.get(name=subject)# wybór z listy
        date_str = request.POST['date']# wyswietlanie listy
        date = parse_date(date_str)#pobranie z formularza
        present = request.POST['present']# wyswietlanie listy
        if present == "obecny":
            isPresent = True
        else:
            isPresent = False
        Frequency.objects.create(student=student,subject=subject,date=date,present=isPresent)# stworzenie wpisu do bazy
        students = User.objects.filter(groups__name = "Students")# pzeszukanie bazy
        subjects = Subject.objects.all() # przeszukanie bazy
        context = {
            'students':students,
            'subjects':subjects,
        }
        return render(request, 'diary/frequency_t.html', context) # zwrócenie do templates
    else:
        is_counted = False
        students = User.objects.filter(groups__name = "Students")# przeszukanie bazy
        subjects = Subject.objects.all()# przeszukanie bazy
        context = {
            'students':students,
            'subjects':subjects,
        }
        return render(request, 'diary/frequency_t.html',context) #zwrócenie do templates

diary/templates/diary/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  {% load auth__extras %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'diary/style2.css' %}" />
  <title>{% block title %}Dziennik Elektroniczny{% endblock %}</title>
</head>
<body>
  <header>
    <br>
    <center><h1>Dziennik elektroniczny</h1></center>
    <br>
    <div id="menu">
      <ul>
        {% if request.user|has_group:"Students" %}
          <li><a href="{% url 'diary:marks' %}">Oceny</a></li>
          <li><a href="{% url 'diary:frequency' %}">Frekwencja</a></li>
          <li><a href="{% url 'diary:teachers' %}">Lista Nauczycieli</a></li>
          <li><a href="{% url 'diary:students' %}">Lista Uczniów</a></li>
          <li style="float:right"><a href="{% url 'diary:login' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'diary:marks_t' %}">Oceny</a></li>
          <li><a href="{% url 'diary:frequency_t' %}">Frekwencja</a></li>
          <li><a href="{% url 'diary:teachers' %}">Lista Nauczycieli</a></li>
          <li><a href="{% url 'diary:students' %}">Lista Uczniów</a></li>
          <li style="float:right"><a href="{% url 'diary:login' %}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </header>
  
  <main>
    <div id="container">
      <h2>Welcome, {{ user.username }} !</h2>
      {% block content %} {% endblock %}
    </div>
  </main>
  
  <footer>
    <div id="footer_left">
        Wykonali: Kamil Oleksy, Pavel Nasytka, Adrian Łupiński
    </div>
    <div id="footer_right">
        Copyright 2017. All right reserved
    </div>
  </footer>
</body>
</html>

diary/templates/diary/frequency.html
{% extends 'diary/base.html' %}

{% block title %}Frequency{% endblock %}

{% block content %}
    <table align="center">
        <tr>
            <th>Data</th>
            <th>Przedmiot</th>
            <th>Obecność</th>
        </tr>
        {% for f in frequency %}
            {% if today.month == f.date.month %}
                <tr>
                    <td>{{ f.date }}</td>
                    <td>{{ f.subject.name }}</td>
                    <td>{{ f.present }}</td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
{% endblock %}

diary/templates/diary/frequency_t.html
{% extends 'diary/base.html' %}

{% block title %}Frequency{% endblock %}

{% block content %}
    <div class="frequency">
        <div class="frequency2">
        <form action="{% url 'diary:frequency_t' %}" method="post">
        {% csrf_token %}
        <h3>Obecność ucznia:</h3></br>
        Student: 
        <select name="students">
            {% for s in students %}
                    <option value="{{s}}" >{{s.first_name}} {{s.last_name}}</option>
            {% endfor %}
        </select></br>
        Przedmiot: 
        <select name="subjects">
            {% for s in subjects %}
                    <option value="{{s}}" >{{s.name}}</option>
            {% endfor %}
        </select></br>
        Data: 
        <input type="date" name="date" size="5%" placeholder="YYYY-MM-DD"></br>
        <input type="radio" name="present" value="obecny" checked="checked"> Obecny
        <input type="radio" name="present" value="nieobecny"> Nieobecny</br></br>
        <input type="submit" value="Zatwierdź">
        </form>
        </div>
    </div>
{% endblock %}

diary/templates/diary/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'diary/style.css' %}" />
  <title>{% block title %}Dziennik Elektroniczny{% endblock %}</title>
</head>
<body>
  <header>
    <center><h1>Dziennik elektroniczny</h1></center>
  </header>
  
  <main>
    <div class="login">
    <div id="container">
      <form action="{% url 'diary:login' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div id="container2">
          <input type="submit" value="Log in">
        </div>
     </form>
    </div>
    </div>
  </main>

  <footer>
    <div id="footer_left">
        Wykonali: Kamil Oleksy, Pavel Nasytka, Adrian Łupiński
    </div>
    <div id="footer_right">
        Copyright 2017. All right reserved
    </div>
  </footer>
</body>
</html>

diary/templates/diary/marks.html
{% extends 'diary/base.html' %}

{% block title %}Marks{% endblock %}

{% block content %}
    <table align="center">
        <tr>
              <th>Przedmioty</th>
              <th>Oceny</th>
              <th>Komentarz</th>
          </tr>
        {% for s in subjects %}
        <tr>
            <td>{{ s.name }}</td>
            <td>
                {% for m2 in marks %}
                    {% if s.name == m2.subject.name %}
                        {{ m2.mark }},
                    {% endif %}
                {% endfor %}
            </td>
            <td>
                {% for m2 in marks %}
                    {% if s.name == m2.subject.name %}
                        {{ m2.comment }},
                    {% endif %}
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

diary/templates/diary/marks_t.html
{% extends 'diary/base.html' %}

{% block title %}Marks{% endblock %}

{% block content %}
    <div class="marks">
        <div class="marks2">
        <form action="{% url 'diary:marks_t'  %}" method="post">
        {% csrf_token %}
        <h3>Dodaj ocenę dla ucznia:</h3></br>
        Student: 
        <select name="students">
            {% for s in students %}
                    <option value="{{s}}" >{{s.first_name}} {{s.last_name}}</option>
            {% endfor %}
        </select></br>
        Przedmiot: 
        <select name="subjects">
            {% for s in subjects %}
                    <option value="{{s}}" >{{s.name}}</option>
            {% endfor %}
        </select></br>
        Ocena: 
        <input type="text" name="mark" size="3%" placeholder="[1,2,3,4,5,6]"></br>
        Komentarz:
        <input type="text" name="comment" size="2%" placeholder="[s,k,w,pd]"></br></br>
        <input type="submit" value="Dodaj"> 
        </form>
        </div>                        
    </div>
{% endblock %}

diary/templates/diary/students.html
{% extends 'diary/base.html' %}

{% block title %}Students{% endblock %}

{% block content %}
    <table align="center">
        <tr>
            <th>Imie</th>
            <th>Nazwisko</th>
            <th>E-mail</th>
        </tr>
        {% for s in students %}
        <tr>
            <td>{{ s.first_name }}</td>
            <td>{{ s.last_name }}</td>
            <td>{{ s.email }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

diary/templates/diary/teachers.html
{% extends 'diary/base.html' %}

{% block title %}Teachers{% endblock %}

{% block content %}
     
    <table align="center">
        <tr>
            <th>Imie</th>
            <th>Nazwisko</th>
            <th>E-mail</th>
        </tr>
        {% for t in teachers %}
        <tr>
            <td>{{ t.first_name }}</td>
            <td>{{ t.last_name }}</td>
            <td>{{ t.email }}</td>
        </tr>
        {% endfor %}
    </table>
    
{% endblock %}